//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentsTestTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arrival
    {
        public int id { get; set; }
        public System.DateTime Arrival_Date { get; set; }
        public double Arrival_Amount { get; set; }
        public double Remains { get; set; }
    }
}
