//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentsTestTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int id { get; set; }
        public int Order_id { get; set; }
        public int Arrival_id { get; set; }
        public Nullable<double> Payment_Amount { get; set; }
    }
}
